# Generated by Django 4.2.25 on 2025-10-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rewiews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('count_stars', models.IntegerField(default=5, verbose_name='Количество звёзд')),
                ('image', models.ImageField(upload_to='media/img/rewiew/', verbose_name='Фото товара')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст отзыва')),
                ('date', models.DateField(default='31.12.2021', verbose_name='Дата написания отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
