# Generated by Django 4.2.25 on 2025-10-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewiews',
            new_name='Reviews',
        ),
    ]
