# Generated by Django 4.2.25 on 2025-10-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviews_count_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='count_stars',
            field=models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], default=5, max_length=5, verbose_name='Количество звёзд'),
        ),
    ]
