# Generated by Django 4.2.25 on 2025-10-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('coast', models.CharField(max_length=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото товара')),
            ],
        ),
    ]
