# Generated by Django 4.2.25 on 2025-10-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_order_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.CharField(choices=[('console', 'Приставки'), ('accessory', 'Аксессуары'), ('subscription', 'Подписки')], default='console', max_length=50),
        ),
    ]
