# Generated by Django 4.2.25 on 2025-10-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_order_category_catalog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='category',
            field=models.CharField(choices=[('console', 'Приставки'), ('accessory', 'Аксессуары'), ('subscription', 'Подписки')], default='console', max_length=50, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
